# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

remote_write:
  - url: "http://192.168.18.70:8086/api/v1/prom/write?u=prome&p=pr0m3&db=prometheus"
 # Remote read configuration (for InfluxDB only at the moment).
remote_read:
  - url: "http://192.168.18.70:8086/api/v1/prom/read?u=prome&p=pr0m3&db=prometheus"


# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

#     static_configs:
#          - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

 #SNMP Palo Alto Exporter

  - job_name: 'PASNMP'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.101.230 # Palo Alto 01
        - 192.168.101.231 # Palo Alto 02
    metrics_path: /snmp
    params:
     module: [paloalto_fw]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '192.168.18.13:9116'  # SNMP exporter.

  - job_name: '9300SNMP'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.18.2 # switches core
    metrics_path: /snmp
    params:
     module: [if-mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '192.168.18.13:9116'  # SNMP exporter.

  - job_name: 'hpmsa'
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: "http"
    static_configs:
    - targets:
      - 192.168.101.42
    relabel_configs:
      - source_labels: [__address__]
        separator: ";"
        regex: (.*)
        target_label: __param_target
        replacement: $1
        action: replace
      - source_labels: [__param_target]
        separator: ";"
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: "192.168.18.13:9114"
        action: "replace"

  - job_name: 'vmware_esx'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '192.168.18.80'       
    params:
      section: [esx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  192.168.18.13:9275

 # - job_name: 'vmware_esx'
 #   metrics_path: '/metrics'
 #   file_sd_configs:
 #   - files:
 #      - /etc/prometheus/esx.yml
 #   params:
 #     section: [esx]
 #   relabel_configs:
 #     - source_labels: [__address__]
 #       target_label: __param_target
 #     - source_labels: [__param_target]
 #       target_label: instance
 #     - target_label: __address__
 #       replacement: 192.168.8.13:9272