default:
  vsphere_host: 192.168.18.80
  vsphere_user: 'root'
  vsphere_password: 'pr1m4r1*'
  ignore_ssl: True
  specs_size: 5000
  collect_only:
    vms: True
    vmguests: True
    datastores: True
    hosts: True
    snapshots: True

esx:
  vsphere_host: 192.168.18.80
  vsphere_user: 'root'
  vsphere_password: 'pr1m4r1*'
  ignore_ssl: True
  specs_size: 5000
  collect_only:
    vms: True
    vmguests: True
    datastores: True
    hosts: True
    snapshots: True
